
spring.datasource.url=jdbc:postgresql://dpg-d9787pcvikkc73dqo9pg-a.oregon-postgres.render.com:5432/url_shortener_db_s4f0

spring.datasource.username=url_shortener_db_s4f0_user
spring.datasource.password=LTM8IgSuRsjra6QIIdBgXwVGe4MrkZSD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect