spring.application.name=kartik
server.port=8080

# ===============================
# PostgreSQL Database Connection
# ===============================
spring.datasource.url=jdbc:postgresql://url_shortener_db_s4f0_user:LTM8IgSuRsjra6QIIdBgXwVGe4MrkZSD@dpg-d9787pcvikkc73dqo9pg-a.oregon-postgres.render.com/url_shortener_db_s4f0
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate Settings
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true